//LOCALHOST
### Get all users
GET http://localhost:3000/contacts

### Get first contact by id

GET http://localhost:3000/contacts/687b09b45a05507335d03144

### Get second contact by id

GET http://localhost:3000/contacts/687b0a315a05507335d03145

### Get third contact by id

GET http://localhost:3000/contacts/687b0a635a05507335d03146

### Create contact

POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Test1",
  "lastName": "Test1",
  "email": "test1@example.com",
  "favoriteColor": "red",
  "birthday": "1990-01-01",
  
  //"email": "test1@example.com",
  "username": "test1@test.com",
  "name": "Hello1",
  "ipAddress": "94.121.168.53"
}

###   Edit contact

PUT http://localhost:3000/contacts/689033998936d96b1cb6cbc0 HTTP/1.1
Content-Type: application/json

{
  "email": "test5@example.com",
  "username": "test5@test.com",
  "name": "Hello5",
  "ipAddress": "95.125.168.55"
}

### Delete contact

DELETE http://localhost:3000/contacts/68901d999892ed4043b5718e
