GET http://localhost:3000/contacts

###

GET http://localhost:3000/contacts/687b09b45a05507335d03144

###

GET http://localhost:3000/contacts/687b0a315a05507335d03145

###

GET http://localhost:3000/contacts/687b0a635a05507335d03146

###

POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "New",
  "lastName": "Contact",
  "email": "new.contact@example.com",
  "favoriteColor": "yellow",
  "birthday": "2000-01-01"
}

###

PUT http://localhost:3000/contacts/687b09b45a05507335d03144
Content-Type: application/json

{
  "firstName": "Alberto",
  "lastName": "Faubel",
  "email": "alberto.faubel@example.com",
  "favoriteColor": "blue",
  "birthday": "1956-06-12"
}

###

DELETE http://localhost:3000/contacts/687b09b45a05507335d03144
